# Generated by Django 2.1.7 on 2019-03-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190306_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='category',
        ),
    ]
