# Generated by Django 2.1.7 on 2019-03-08 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_remove_pattern_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="pattern",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budget.Pattern",
                to_field="pattern",
            ),
        ),
    ]
