# Generated by Django 2.1.7 on 2019-03-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_transaction_pattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True, verbose_name="Date")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Balance"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="subcategory", options={"ordering": ["category_id", "name"]},
        ),
        migrations.AddField(
            model_name="account",
            name="annual_fee",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Annual Fee"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_line",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Credit Line"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="date_opened",
            field=models.DateField(auto_now=True, verbose_name="Date Opened"),
        ),
        migrations.AddField(
            model_name="account",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Interest Rate",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="minimum_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=9,
                verbose_name="Minimum Payment",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Priority"),
        ),
        migrations.AddField(
            model_name="account",
            name="statement_date",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Statement Date"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Account",
                to_field="name",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="holder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.AccountHolder",
                to_field="name",
            ),
        ),
    ]
