# Generated by Django 2.1.7 on 2019-03-11 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_auto_20190310_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_opened",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date Opened"
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
