# Generated by Django 2.1.7 on 2019-03-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0013_auto_20190319_0725"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="holder_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.AccountHolder",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="holder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_legacy",
                to="budget.AccountHolder",
                to_field="name",
            ),
        ),
    ]
