# Generated by Django 2.1.7 on 2019-03-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_remove_account_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='holder_new',
            new_name='holder',
        ),
    ]
