# Generated by Django 2.1.7 on 2019-03-20 15:05

import django.db.models.deletion
from django.db import migrations, models


def reassign_fks(apps, schema_editor):
    Pattern = apps.get_model("budget", "Pattern")
    Statement = apps.get_model("budget", "Statement")
    Subcategory = apps.get_model("budget", "Subcategory")
    Transaction = apps.get_model("budget", "Transaction")
    Upload = apps.get_model("budget", "Upload")
    db_alias = schema_editor.connection.alias

    for p in Pattern.objects.using(db_alias).all():
        p.subcategory_new_id = p.subcategory.id
        p.save()

    for s in Statement.objects.using(db_alias).all():
        s.account_new_id = s.account.id
        s.save()

    for sc in Subcategory.objects.using(db_alias).all():
        sc.category_new_id = sc.category.id
        sc.save()

    for t in Transaction.objects.using(db_alias).all():
        t.account_new_id = t.account.id
        t.category_new_id = t.category.id
        t.subcategory_new_id = t.subcategory.id
        t.pattern_new_id = t.pattern.id
        t.save()

    for u in Upload.objects.using(db_alias).all():
        u.account_new_id = u.account.id
        u.save()


def unassign_fks(apps, schema_editor):
    Pattern = apps.get_model("budget", "Pattern")
    Statement = apps.get_model("budget", "Statement")
    Subcategory = apps.get_model("budget", "Subcategory")
    Transaction = apps.get_model("budget", "Transaction")
    Upload = apps.get_model("budget", "Upload")
    db_alias = schema_editor.connection.alias

    for p in Pattern.objects.using(db_alias).all():
        p.subcategory_new_id = None
        p.save()

    for s in Statement.objects.using(db_alias).all():
        s.account_new_id = None
        s.save()

    for sc in Subcategory.objects.using(db_alias).all():
        sc.category_new_id = None
        sc.save()

    for t in Transaction.objects.using(db_alias).all():
        t.account_new_id = None
        t.category_new_id = None
        t.subcategory_new_id = None
        t.pattern_new_id = None
        t.save()

    for u in Upload.objects.using(db_alias).all():
        u.account_new_id = None
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0016_auto_20190319_0740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pattern",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pattern_legacy",
                to="budget.Subcategory",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statement_legacy",
                to="budget.Account",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcat_legacy",
                to="budget.Category",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transacc_legacy",
                to="budget.Account",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcat_legacy",
                to="budget.Category",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="pattern",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transpat_legacy",
                to="budget.Pattern",
                to_field="pattern",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transsub_legacy",
                to="budget.Subcategory",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_legacy",
                to="budget.Account",
                to_field="name",
            ),
        ),
        migrations.AddField(
            model_name="pattern",
            name="subcategory_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Subcategory",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="account_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Account",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Category",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="category_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Category",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pattern_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budget.Pattern",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="subcategory_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Subcategory",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="account_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.Account",
            ),
        ),
        migrations.RunPython(reassign_fks, unassign_fks),
    ]
