# Generated by Django 2.1.7 on 2019-03-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20190320_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category_new_id', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('account_new', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account_new', 'date', 'amount', 'description')},
        ),
    ]
