# Generated by Django 2.1.7 on 2019-03-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_auto_20190320_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category_id', 'name']},
        ),
        migrations.RenameField(
            model_name='pattern',
            old_name='subcategory_new',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='account_new',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_new',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_new',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category_new',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='pattern_new',
            new_name='pattern',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='subcategory_new',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='account_new',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together={('account', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'date', 'amount', 'description')},
        ),
    ]
