# Generated by Django 2.1.7 on 2019-03-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_auto_20190329_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['class_field_id', 'name'], 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AlterModelOptions(
            name='transactionclass',
            options={'verbose_name_plural': 'transaction classes'},
        ),
    ]
