# Generated by Django 2.1.7 on 2019-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0032_auto_20190331_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-upload_time']},
        ),
    ]
