# Generated by Django 2.2.3 on 2019-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0037_remove_account_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
