# Generated by Django 2.2.3 on 2019-07-13 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0038_delete_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("csv", models.FileField(null=True, upload_to="csvs")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
