# Generated by Django 2.2.3 on 2019-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0039_csvbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvbackup',
            name='csv',
            field=models.FileField(null=True, upload_to='csvs', verbose_name='CSV'),
        ),
    ]
