version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/simplefi/src
    networks:
      - server_network
      - database_network
    depends_on:
      - postgres

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - server_network

  postgres:
    image: postgres:10
    env_file:
      - config/postgres/db1_env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

networks:
  server_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
