[tool.black]
line-length = 88
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | venv
    | .*/migrations
  )/
)
'''

[tool.isort]
profile = "black"
src_paths = ["simplefi", "budget", "debt"]
