# Generated by Django 2.1.7 on 2019-03-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='name',
        ),
    ]
