# Generated by Django 2.1.7 on 2019-03-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20190311_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='minimum_payment',
        ),
        migrations.AddField(
            model_name='account',
            name='min_pay_dlr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Minimum Payment ($)'),
        ),
        migrations.AddField(
            model_name='account',
            name='min_pay_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Minimum Payment (%)'),
        ),
    ]
