# Generated by Django 2.1.7 on 2019-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20190311_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9, verbose_name='Interest Rate (%)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='min_pay_pct',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9, verbose_name='Minimum Payment (%)'),
        ),
    ]
