# Generated by Django 2.1.7 on 2019-03-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20190319_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='holder',
        ),
    ]
