# Generated by Django 2.1.7 on 2019-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_auto_20190320_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('income', 'Income'), ('discretionary', 'Discretionary'), ('bills', 'Bills'), ('debt', 'Debt'), ('savings', 'Savings')], max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
