# Generated by Django 2.1.7 on 2019-03-26 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0023_auto_20190325_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TransactionClass',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['class_field_id', 'name']},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='class_field',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='class_field',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('user', 'class_field', 'name')},
        ),
    ]
