# Generated by Django 2.1.7 on 2019-03-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_auto_20190325_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionclass',
            name='budget',
        ),
    ]
