# Generated by Django 2.1.7 on 2019-03-26 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0025_remove_transactionclass_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'upload_id', 'date', 'amount', 'description')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subcategory',
        ),
    ]
