# Generated by Django 2.1.7 on 2019-03-31 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0028_auto_20190330_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'date', 'amount', 'description')},
        ),
    ]
