# Generated by Django 2.1.7 on 2019-03-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_auto_20190331_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='upload_id',
            new_name='upload',
        ),
    ]
