# Generated by Django 2.1.7 on 2019-04-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0033_auto_20190407_0852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountholder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accountholder',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='statement',
            name='account',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_line',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_opened',
        ),
        migrations.RemoveField(
            model_name='account',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_pay_dlr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_pay_pct',
        ),
        migrations.RemoveField(
            model_name='account',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='account',
            name='statement_date',
        ),
        migrations.DeleteModel(
            name='AccountHolder',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
