# Generated by Django 2.1.7 on 2019-04-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_auto_20190414_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Transaction date'),
        ),
    ]
