# Generated by Django 2.2.2 on 2019-07-01 13:05

from django.db import migrations, models


def create_accountholders(apps, schema_editor):
    """Create account holder objects and attach them via FK."""
    AccountHolder = apps.get_model('debt.AccountHolder')
    CreditLine = apps.get_model('debt.CreditLine')
    db_alias = schema_editor.connection.alias

    # Set field for each CL object
    for cl in CreditLine.objects.using(db_alias).all():
        cl.holder, __ = AccountHolder.objects.using(db_alias).get_or_create(
            user=cl.user,
            name=cl.account_holder)
        cl.save()


def add_holders_to_accounts(apps, schema_editor):
    """Set account_holder field from FK."""
    CreditLine = apps.get_model('debt.CreditLine')
    db_alias = schema_editor.connection.alias

    # Set field for each CL object
    for cl in CreditLine.objects.using(db_alias).all():
        cl.account_holder = cl.holder.name
        cl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditline',
            name='account_holder',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_holders_to_accounts,
            create_accountholders
        ),
    ]
