# Generated by Django 2.2.2 on 2019-07-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_creditline_account_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditline',
            name='holder',
        ),
        migrations.DeleteModel(
            name='AccountHolder',
        ),
    ]
