# Generated by Django 2.2.2 on 2019-07-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_remove_creditline_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditline',
            old_name='account_holder',
            new_name='holder',
        ),
    ]
