# Generated by Django 2.2.3 on 2019-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_auto_20190701_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='holder',
            field=models.CharField(max_length=255, verbose_name='Holder'),
        ),
    ]
